import {useEffect,useState} from 'react';
import {api} from './api';
import {Button,Field,Notice,money} from './ui';
export const localMonth=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;};
interface Budget{category:string;limitCents:number;spentCents:number}
export function BudgetsScreen(){
  const [month,setMonth]=useState(localMonth());const [rows,setRows]=useState<Budget[]>([]);const [error,setError]=useState('');const [message,setMessage]=useState('');
  useEffect(()=>{api<Budget[]>(`/budgets?month=${month}`).then(setRows).catch(err=>setError(err.message));},[month]);
  return <><p className="eyebrow">MAKE ROOM FOR WHAT MATTERS</p><h1>Monthly budgets</h1><p>Category spending counts confirmed line totals. Receipt-level tax and adjustments are excluded.</p><Field label="Budget month" type="month" value={month} required onChange={e=>setMonth(e.target.value)}/>{error && <Notice error>{error}</Notice>}{message && <Notice>{message}</Notice>}<div className="grid">{rows.map(row=><form className="card" key={row.category} onSubmit={async e=>{e.preventDefault();const text=String(new FormData(e.currentTarget).get('limit'));const match=/^(\d{1,7})(?:\.(\d{1,2}))?$/.exec(text);if(!match){setError('Enter a valid CAD amount.');return;}const limitCents=Number(match[1])*100+Number((match[2]??'').padEnd(2,'0'));try{await api(`/budgets/${row.category}/${month}`,{method:'PUT',body:JSON.stringify({limitCents})});setRows(prev=>prev.map(b=>b.category===row.category?{...b,limitCents}:b));setMessage(`${row.category} budget saved.`);setError('');}catch(err){setError((err as Error).message);}}}><h2>{row.category}</h2><p>{money(row.spentCents)} spent</p><progress max={Math.max(row.limitCents,1)} value={Math.min(row.spentCents,row.limitCents)} aria-label={`${row.category} budget used`}/><p>{row.limitCents ? row.spentCents>row.limitCents ? `${money(row.spentCents-row.limitCents)} over budget`:`${money(row.limitCents-row.spentCents)} remaining`:'No budget set'}</p><Field label={`${row.category} limit (CAD)`} name="limit" type="number" step="0.01" min="0" max="9999999.99" defaultValue={(row.limitCents/100).toFixed(2)} key={month+row.limitCents} required/><Button>Save budget</Button></form>)}</div></>;
}
