import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from './api';
import { Badge, Button, Empty, Field, Notice, money } from './ui';
interface ReceiptRow { id: string; rawMerchant: string; purchaseDate: string; totalCents: number; status: string }
export function ReceiptsScreen() {
  const [from,setFrom]=useState('');const [to,setTo]=useState('');
  const [month, setMonth] = useState(''); const [merchant, setMerchant] = useState(''); const [status, setStatus] = useState(''); const [page, setPage] = useState(1);
  const [result, setResult] = useState<{items: ReceiptRow[]; total:number}>(); const [error, setError] = useState('');
  useEffect(() => { let active = true; setError(''); const query = new URLSearchParams({page:String(page)}); if(from)query.set('from',from);if(to)query.set('to',to); if (month) query.set('month',month); if (merchant) query.set('merchant',merchant); if (status) query.set('status',status); api<{items:ReceiptRow[];total:number}>(`/receipts?${query}`).then(data => {if(active) setResult(data);}).catch(err => {if(active) setError(err.message);}); return () => {active=false;}; }, [month,merchant,status,page,from,to]);
  return <><p className="eyebrow">YOUR PURCHASE NOTEBOOK</p><h1>Receipt history</h1><div className="actions"><Link className="button" to="/upload">Scan a receipt</Link><Link to="/receipts/new">Enter manually</Link></div><div className="card row"><Field label="Purchase month" type="month" value={month} onChange={e => {setMonth(e.target.value);setPage(1);}}/><Field label="From date" type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1);}}/><Field label="To date" type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1);}}/><Field label="Search merchant" value={merchant} onChange={e => {setMerchant(e.target.value);setPage(1);}}/><label className="field">Status<select value={status} onChange={e => {setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option>{['confirmed','needs_review','processing','failed'].map(s => <option key={s}>{s}</option>)}</select></label></div>{error && <Notice error>{error}</Notice>}{!result ? <Notice>Loading receiptsâ€¦</Notice> : !result.items.length ? <Empty title="No matching receipts"><p>Add a receipt or adjust your filters.</p></Empty> : <section className="card table-scroll"><table><thead><tr><th>Merchant</th><th>Purchase date</th><th>Recorded total (CAD)</th><th>Status</th></tr></thead><tbody>{result.items.map(r => <tr key={r.id}><td><Link to={`/receipts/${r.id}`}>{r.rawMerchant || 'Unreviewed scan'}</Link></td><td>{r.purchaseDate || 'Needs review'}</td><td>{money(r.totalCents)}</td><td><Badge>{r.status}</Badge></td></tr>)}</tbody></table></section>}{result && <div className="actions"><Button className="secondary" disabled={page===1} onClick={() => setPage(p=>p-1)}>Previous</Button><span>Page {page} Â· {result.total} receipts</span><Button className="secondary" disabled={page*20>=result.total} onClick={() => setPage(p=>p+1)}>Next</Button></div>}</>;
}

